# Mac Setup
# wget https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.110.0/otelcol-contrib_0.110.0_darwin_amd64.tar.gz
# tar -xvf otelcol-contrib_0.110.0_darwin_amd64.tar.gz
# ./otelcol-contrib --config otel_collector_config.yaml

receivers:
  otlp:
    protocols:
      grpc:
        # The gRPC endpoint where the OTLP receiver listens for incoming trace data.
        endpoint: 127.0.0.1:4317
      http:
        # The HTTP endpoint where the OTLP receiver listens for incoming trace data.
        endpoint: 127.0.0.1:4318

processors:
  # The batch processor is responsible for aggregating incoming
  # telemetry data into batches before sending it to exporters.
  batch:

exporters:
  # Sets the logging level to debug, which provides detailed
  # information about the telemetry data being exported.
  logging:
    loglevel: debug

service:
  pipelines:

    traces:
      # Specifies that this pipeline will use the OTLP receiver to collect trace data.
      receivers: [otlp]
      # Indicates that the batch processor will be applied to incoming trace data for aggregation.
      processors: [batch]
      # Specifies that processed trace data will be exported using the logging exporter.
      exporters: [logging]

    metrics:
      # Specifies that this pipeline will use the OTLP receiver to collect metric data.
      receivers: [otlp]
      # Specifies that processed metric data will be exported using the logging exporter.
      exporters: [logging]

    logs:
      # Specifies that this pipeline will use the OTLP receiver to collect log data.
      receivers: [otlp]
      # Specifies that processed log data will be exported using the logging exporter.
      exporters: [logging]

